projects:
  rent:
    schemaPath: src/graphql/schema.json
    includes:
      - 'yes'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
extensions:
  amplify:
    version: 3
